### ISSUE TITLE
The role cannot be run in separation using a tag

### ISSUE THREAD

**Issue by ltarasiewicz** [infOpen/ansible-role-apache#5]
Hi,

I found this bug that when you attempt to run this role in separation, e.g. when you tag this one with 

```
...
...
- { role: achaussier.apache, tags: [apache] }
...
```

Then you execute the playbook with only the `apache` tag, the role would fail with:

> TASK: [achaussier.apache | install apache packages] **************************\* 
> fatal: [my host] => with_items expects a list or a set

This is probably due to the fact that in here:

```
- name: Load the OS specific varibles
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family }}.yml"

- include: install_debian.yml
  tags:
    - install
    - apache
  when: ansible_os_family == "Debian"
```

(https://github.com/infOpen/ansible-role-apache/blob/master/tasks/main.yml#L5-L12)

you attach tags `install` and `apache` on the `include` task, so consequently the "Load OS specific variables" is skipped when executing only `apache` tag.

When you attach `apache` tag to "Load OS specific variables" or get rid of tags all together in "- include: install_debian.yml", it works.
